btn=tkinter.Button(window,text="<<Previous (slow)",width=50)
# btn.pack()
# btn=tkinter.Button(window,text="Next>> (slow)",width=50)
# btn.pack()
# btn=tkinter.Button(window,text="Next>> (fast)",width=50)
# btn.pack()
# btn=tkinter.Button(window,text="Give Out ",width=50)
# btn.pack()
# btn=tkinter.Button(window,text="Give Not Out ",width=50)
# btn.pack()
